### ISSUE TITLE
make api requests using authentication

### ISSUE THREAD

**Issue by xaviersalazar** [xaviersalazar/check-exercises-app#11]
## Problem:

Currently the app is making the API calls without any authentication. The rate-limit for un-authenticated requests is 60 per hour. Which works for now, but each time you press the `check my missing exercises` button, the app makes 4 calls, with more calls to come for the java and sql section. 60 requests per hour may work for one person, but if the entire class is trying to use the app, at 4+ calls each time, you may exceed the limit. 

## Goal:
Change the app so that you have to authenticate your github account by entering your username and password

**Comment by cptcrunchy** [comment]
This issue can be resolved quickly by integrating AuthO into the [Github App](https://auth0.com/docs/connections/social/github). I could help with this Issue but I'm not an admin.

**Comment by cptcrunchy** [comment]
This is also a good guideline. Directly from Github. [HERE](https://developer.github.com/v3/guides/basics-of-authentication/)

**Comment by xaviersalazar** [comment]
I'll take this issue myself, since you have to register this application in the Developer Settings for OAuth

**Comment by xaviersalazar** [comment]
This issue has been resolved
