### ISSUE TITLE
Doesn't seem to work between cohorts and throws 404 not found error when repo has not been created yet

### ISSUE THREAD

**Issue by Hunter-Houts** [xaviersalazar/check-exercises-app#17]
it shows that I don't have a codeup-web-exercises repo, but I do: https://github.com/Hunter-Houts/codeup-web-exercises

needs to account for new cohorts that do not yet have repos such as codeup-java-exercises or database-exercises.

**Comment by xaviersalazar** [comment]
This issue has been resolved
