### ISSUE TITLE
add event listener enter key pressed

### ISSUE THREAD

**Issue by xaviersalazar** [xaviersalazar/check-exercises-app#2]
## Problem:
As of now, if you press the `enter` key after entering your github name, nothing will happen. 

## Goal:
Add a a listener that also detects the `enter` key as an alternative to pressing the `check my missing exercises` button

**Comment by cptcrunchy** [comment]
Was this solved with PR #14?

**Comment by xaviersalazar** [comment]
@cptcrunchy  You are correct. Forgot to close this issue. Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
