### ISSUE TITLE
update java section

### ISSUE THREAD

**Issue by xaviersalazar** [xaviersalazar/check-exercises-app#4]
## Problem:
The app currently shows all java files as missing. This is because there isn't an API call to the codeup-java-exercises to grab the java files in that repo. 

## Goal:
Update the app to make the API call and correctly display the missing java exercises

**Comment by cptcrunchy** [comment]
I'm currently trying to implement an async function to map over an array of URLs so that more URLs can be added easily.

**Comment by xaviersalazar** [comment]
Issue has been resolved
